# Generated by Django 2.2.2 on 2019-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sell_quant',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
