# Generated by Django 2.2.2 on 2019-06-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0002_auto_20190626_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='initial_quant',
            field=models.DecimalField(decimal_places=2, default=123, max_digits=10),
            preserve_default=False,
        ),
    ]
