# Generated by Django 2.2.2 on 2019-06-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0004_auto_20190626_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell_quant',
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=models.DecimalField(decimal_places=2, max_digits=10), null=True),
        ),
    ]
