# Generated by Django 2.2.2 on 2019-06-26 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0006_auto_20190627_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell_quant',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MaxValueValidator(models.DecimalField(decimal_places=2, max_digits=10))]),
        ),
    ]
