# Generated by Django 2.2.2 on 2019-06-26 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0008_auto_20190627_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='sell_quant',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(models.FloatField())]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_quant',
            field=models.FloatField(),
        ),
    ]
