# Generated by Django 2.2.2 on 2019-06-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_portfolio', '0011_auto_20190627_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='initial_quant',
        ),
    ]
